### ISSUE TITLE
STT not finishing sentences and not understanding me

### ISSUE THREAD

**Issue by MrJasperge** [MartLugt/PWS#10]
Jarvis
Play guess the number
_What should be the maximum v-_
55
_Guess a number between zero and fiftyf-_
20
_... Guess hi-_
30
_Sorry, couldn't quite catch -_
30
_..._
`('guess', 0.6666666666666666)
Recording Activated
Recording is done
{'alternative': [{'confidence': 0.76802278, 'transcript': '55'}, {'transcript': 'fifty five'}, {'transcript': '50 V'}, {'transcript': '50/5'}, {'transcript': 'fifty-five'}], 'final': True}
Recording Activated
Recording is done
{'alternative': [{'confidence': 0.85899514, 'transcript': '20'}, {'transcript': 'xx'}, {'transcript': 'twenty'}, {'transcript': '2nd'}, {'transcript': 'plenty'}], 'final': True}
Recording Activated
Recording is done
[]
Recording Activated
Recording is done
30
30
Traceback (most recent call last):
  File "assistant.py", line 53, in <module>
    detect()
  File "assistant.py", line 49, in detect
    detector.start(detected_callback=callback, sleep_time=0.03)
  File "/home/pi/Documents/PWS/snowboydecoder.py", line 200, in start
    callback()
  File "assistant.py", line 41, in callback
    main()
  File "assistant.py", line 35, in main
    commands.execute(intent, text)
  File "/home/pi/Documents/PWS/commands.py", line 376, in execute
    number_guess(text)
  File "/home/pi/Documents/PWS/commands.py", line 267, in number_guess
    game(1)
  File "/home/pi/Documents/PWS/commands.py", line 256, in game
    game(turns)
  File "/home/pi/Documents/PWS/commands.py", line 252, in game
    guess = get_num(conversation["no_number_guess"])
  File "/home/pi/Documents/PWS/commands.py", line 236, in get_num
    for res in res_full["alternative"]:
TypeError: 'NoneType' object is not subscriptable`

**Comment by MartLugt** [comment]
Most likely due to the record command cutting of the play commands stream
