### ISSUE TITLE
STT Not understanding

### ISSUE THREAD

**Issue by MrJasperge** [MartLugt/PWS#11]
In guess the number:

_Guess higher_

9

_..._

`Recording Activated
Recording is done
[]
Recording Activated
Recording is done
[]
False
Recording Activated
Recording is done
Not confident
9
9
Traceback (most recent call last):
  File "assistant.py", line 53, in <module>
    detect()
  File "assistant.py", line 49, in detect
    detector.start(detected_callback=callback, sleep_time=0.03)
  File "/home/pi/Documents/PWS/snowboydecoder.py", line 200, in start
    callback()
  File "assistant.py", line 41, in callback
    main()
  File "assistant.py", line 35, in main
    commands.execute(intent, text)
  File "/home/pi/Documents/PWS/commands.py", line 376, in execute
    number_guess(text)
  File "/home/pi/Documents/PWS/commands.py", line 267, in number_guess
    game(1)
  File "/home/pi/Documents/PWS/commands.py", line 260, in game
    game(turns)
  File "/home/pi/Documents/PWS/commands.py", line 260, in game
    game(turns)
  File "/home/pi/Documents/PWS/commands.py", line 260, in game
    game(turns)
  File "/home/pi/Documents/PWS/commands.py", line 252, in game
    guess = get_num(conversation["no_number_guess"])
  File "/home/pi/Documents/PWS/commands.py", line 236, in get_num
    for res in res_full["alternative"]:
TypeError: 'NoneType' object is not subscriptable
`

**Comment by MartLugt** [comment]
closed
