### ISSUE TITLE
STT not waiting for response

### ISSUE THREAD

**Issue by MrJasperge** [MartLugt/PWS#12]
In guess the number:

_Guess a number between 1 and 200_

(2 second delay) hundred

_Sorry, could't quite catch that_

...

`('guess', 0.6666666666666666)
Recording Activated
Recording is done
{'final': True, 'alternative': [{'transcript': '200', 'confidence': 0.60982227}, {'transcript': 'two hundred'}, {'transcript': '2/100'}, {'transcript': 'to 100'}, {'transcript': 'tu100'}]}
Recording Activated
Recording is done
[]
Recording Activated
Recording is done
Not confident
100
100
Traceback (most recent call last):
  File "assistant.py", line 53, in <module>
    detect()
  File "assistant.py", line 49, in detect
    detector.start(detected_callback=callback, sleep_time=0.03)
  File "/home/pi/Documents/PWS/snowboydecoder.py", line 200, in start
    callback()
  File "assistant.py", line 41, in callback
    main()
  File "assistant.py", line 30, in main
    main()
  File "assistant.py", line 35, in main
    commands.execute(intent, text)
  File "/home/pi/Documents/PWS/commands.py", line 376, in execute
    number_guess(text)
  File "/home/pi/Documents/PWS/commands.py", line 267, in number_guess
    game(1)
  File "/home/pi/Documents/PWS/commands.py", line 252, in game
    guess = get_num(conversation["no_number_guess"])
  File "/home/pi/Documents/PWS/commands.py", line 236, in get_num
    for res in res_full["alternative"]:
TypeError: 'NoneType' object is not subscriptable
`

**Comment by MrJasperge** [comment]
Same this time

`('guess', 0.6666666666666666)
Recording Activated
Recording is done
[]
Recording Activated
Recording is done
Not confident
5
5
Traceback (most recent call last):
  File "assistant.py", line 53, in <module>
    detect()
  File "assistant.py", line 49, in detect
    detector.start(detected_callback=callback, sleep_time=0.03)
  File "/home/pi/Documents/PWS/snowboydecoder.py", line 200, in start
    callback()
  File "assistant.py", line 41, in callback
    main()
  File "assistant.py", line 35, in main
    commands.execute(intent, text)
  File "/home/pi/Documents/PWS/commands.py", line 376, in execute
    number_guess(text)
  File "/home/pi/Documents/PWS/commands.py", line 246, in number_guess
    maximum = get_num(conversation["no_number"])
  File "/home/pi/Documents/PWS/commands.py", line 236, in get_num
    for res in res_full["alternative"]:
TypeError: 'NoneType' object is not subscriptable
`

**Comment by MartLugt** [comment]
https://github.com/MartLugt/PWS/issues/10
