### ISSUE TITLE
STT tell me a joke

### ISSUE THREAD

**Issue by MrJasperge** [MartLugt/PWS#5]
Jarvis
Tell me a joke
````
Listening...
First be silent, calibrating silence
We are now recording. Start talking for it to start.
First be silent, calibrating silence
We are now recording. Start talking for it to start.
INFO:snowboy:Keyword 1 detected at time: 2018-02-19 20:51:20
Recording Activated
Recording is done
[]

joke
0
[]
joke joke
Traceback (most recent call last):
  File "assistant.py", line 31, in <module>
    detector.start(detected_callback=callback, sleep_time=0.03)
  File "/home/pi/Documents/PWS/snowboydecoder.py", line 200, in start
    callback()
  File "assistant.py", line 22, in callback
    intent = query_parser.parse(text)
  File "/home/pi/Documents/PWS/query_parser.py", line 40, in parse
    if keyword in text and keyword not in keyword_buffer:
TypeError: argument of type 'bool' is not iterable
````

**Comment by MartLugt** [comment]
fixed
