### ISSUE TITLE
STT unintelligable

### ISSUE THREAD

**Issue by MrJasperge** [MartLugt/PWS#6]
Jarvis
vvwmvvw
`Listening...
First be silent, calibrating silence
We are now recording. Start talking for it to start.
First be silent, calibrating silence
We are now recording. Start talking for it to start.
INFO:snowboy:Keyword 1 detected at time: 2018-02-19 20:57:30
Recording Activated
Recording is done
[]
Recording Activated
Recording is done
[]
Traceback (most recent call last):
  File "assistant.py", line 35, in <module>
    detector.start(detected_callback=callback, sleep_time=0.03)
  File "/home/pi/Documents/PWS/snowboydecoder.py", line 200, in start
    callback()
  File "assistant.py", line 24, in callback
    callback()
  File "assistant.py", line 24, in callback
    callback()
  File "assistant.py", line 17, in callback
    frames = speech_to_text.record(rate = rate, ding = True)
  File "/home/pi/Documents/PWS/speech_to_text.py", line 137, in record
    init()
  File "/home/pi/Documents/PWS/speech_to_text.py", line 34, in init
    frames_per_buffer=BUFFER_SIZE,
  File "/home/pi/.local/lib/python3.5/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9996] Invalid input device (no default output device)
`

**Comment by MartLugt** [comment]
fixed

**Comment by MrJasperge** [comment]
That's awesome! 💯
