### ISSUE TITLE
STT ur mom

### ISSUE THREAD

**Issue by MrJasperge** [MartLugt/PWS#8]
Jarvis offends me by saying 'ur mom' and then 'ur mom gay' I'm so sad rn

`Listening...
First be silent, calibrating silence
We are now recording. Start talking for it to start. TODO: FIX THIS SHIT
First be silent, calibrating silence
We are now recording. Start talking for it to start. TODO: FIX THIS SHIT
First be silent, calibrating silence
We are now recording. Start talking for it to start. TODO: FIX THIS SHIT
First be silent, calibrating silence
We are now recording. Start talking for it to start. TODO: FIX THIS SHIT
First be silent, calibrating silence
We are now recording. Start talking for it to start. TODO: FIX THIS SHIT
First be silent, calibrating silence
We are now recording. Start talking for it to start. TODO: FIX THIS SHIT
First be silent, calibrating silence
We are now recording. Start talking for it to start. TODO: FIX THIS SHIT
INFO:snowboy:Keyword 1 detected at time: 2018-02-20 18:05:32
Recording Activated
Recording is done
[]
Recording Activated
Recording is done
[]
Traceback (most recent call last):
  File "assistant.py", line 38, in <module>
    detector.start(detected_callback=callback, sleep_time=0.03)
  File "/home/pi/Documents/PWS/snowboydecoder.py", line 200, in start
    callback()
  File "assistant.py", line 32, in callback
    main()
  File "assistant.py", line 21, in main
    callback()
  File "assistant.py", line 32, in callback
    main()
  File "assistant.py", line 21, in main
    callback()
  File "assistant.py", line 32, in callback
    main()
  File "assistant.py", line 14, in main
    frames = speech_to_text.record(rate=rate, ding=True)
  File "/home/pi/Documents/PWS/speech_to_text.py", line 137, in record
    init()
  File "/home/pi/Documents/PWS/speech_to_text.py", line 34, in init
    frames_per_buffer=BUFFER_SIZE,
  File "/home/pi/.local/lib/python3.5/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9996] Invalid input device (no default output device)`

When the user doesn't say anything after saying Jarvis, he just calls your mom gay :-1:

**Comment by MrJasperge** [comment]
he's so mean... :((

**Comment by MrJasperge** [comment]
pls fix

**Comment by MrJasperge** [comment]
pls

**Comment by MartLugt** [comment]
fixed
