### ISSUE TITLE
bool is passed to query_parser.parse

### ISSUE THREAD

**Issue by MartLugt** [MartLugt/PWS#9]
```
Traceback (most recent call last):
  File "assistant.py", line 53, in <module>
    detect()
  File "assistant.py", line 49, in detect
    detector.start(detected_callback=callback, sleep_time=0.03)
  File "/home/pi/Documents/PWS/snowboydecoder.py", line 200, in start
    callback()
  File "assistant.py", line 41, in callback
    main()
  File "assistant.py", line 30, in main
    main()
  File "assistant.py", line 32, in main
    intent = query_parser.parse(text.lower())
AttributeError: 'bool' object has no attribute 'lower'
```

```
Traceback (most recent call last):
  File "assistant.py", line 50, in <module>
    detect()
  File "assistant.py", line 47, in detect
    detector.start(detected_callback=callback, sleep_time=0.03)
  File "/home/pi/Documents/PWS/snowboydecoder.py", line 200, in start
    callback()
  File "assistant.py", line 39, in callback
    main()
  File "assistant.py", line 28, in main
    main()
  File "assistant.py", line 28, in main
    main()
  File "assistant.py", line 28, in main
    main()
  File "assistant.py", line 30, in main
    intent = query_parser.parse(text)
  File "/home/pi/Documents/PWS/query_parser.py", line 41, in parse
    if keyword in text and keyword not in keyword_buffer:
TypeError: argument of type 'bool' is not iterable
```

**Comment by MartLugt** [comment]
Might be fixed in commit #6b7de26294e56073c8f944b51e53331d5dc00195
